name: "Terraform Plan"

on:
  pull_request:
    types: [opened, reopened]
  push:
    branches:
    - main

permissions:
  id-token: write # required to use OIDC authentication
  contents: read # required to checkout the code from the repo

jobs:
  terraform:
    name: "Terraform Infrastructure Change Management"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        # We keep Terraform files in the deploy directory.
        working-directory: ./deploy
# steps
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::543051889675:role/githubActionsRole
          role-duration-seconds: 900 # the ttl of the session, in seconds.
          aws-region: eu-central-1 # use your region here.

      - name: Checkout the repository to the runner
        uses: actions/checkout@v3

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6
          terraform_wrapper: false

      - name: Terraform init
        id: init
        run: terraform init

      - name: Terraform workspace select
        id: workspace_select
        run: terraform workspace select dev

      - name: Terraform format
        id: fmt
        run: terraform fmt -check

      - name: Terraform validate
        id: validate
        run: terraform validate

      - name: Terraform plan
        id: plan
        run: terraform plan

      - name: Terraform apply
        id: apply
        run: terraform apply -auto-approve

      - name: Test APIs
        id: testAPIs
        run: cd ../test && sh testAPIs.sh

      - name: Terraform destroy
        if: always() && steps.apply.outcome == 'success'
        id: destroy
        run: terraform destroy -auto-approve

      - name: Terraform workspace select
        id: workspace_prod
        run: terraform workspace select prod

      - name: Terraform plan prod
        id: plan_prod
        run: terraform plan

      - name: Terraform apply prod
        id: apply_prod
        run: terraform apply -auto-approve

      - name: Test APIs
        id: testAPIsShouldFail
        run: cd ../test && sh testAPIs.sh
        continue-on-error: true

      - name: Confirm user email via cli
        id: confirmUserCli
        run: aws cognito-idp admin-update-user-attributes --user-pool-id `terraform output --raw user_pool_id` --username sfrumkinab --user-attributes Name=email_verified,Value=true

      - name: Test APIs
        id: testAPIs_prod
        run: cd ../test && sh testAPIs.sh

      - name: Terraform destroy prod
        if: always() && steps.apply_prod.outcome == 'success'
        id: destroy_prod
        run: terraform destroy -auto-approve


